DROP TABLE IF EXISTS inven;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS emp;

CREATE TABLE inven (
UUID TINYTEXT PRIMARY KEY NOT NULL UNIQUE,
itemid TINYTEXT NOT NULL UNIQUE,
weight INT,
units INT,
Recv DATETIME NOT NULL,
pos INT NOT NULL);

CREATE TABLE job (
UUID TINYTEXT PRIMARY KEY NOT NULL UNIQUE,
opos TINYTEXT NOT NULL UNIQUE,
npos TINYTEXT NOT NULL UNIQUE,
priority ENUM ("high","med","low") DEFAULT '"low"' NOT NULL,
tmov TIMESTAMP NOT NULL,
trans BOOLEAN NOT NULL,
time of deposit TIMESTAMP NOT NULL,
eid INT NOT NULL UNIQUE);

CREATE TABLE item (
itemid TINYTEXT PRIMARY KEY NOT NULL UNIQUE,
profit INT NOT NULL,
moa DATE NOT NULL,
weekend BOOLEAN NOT NULL,
season BOOLEAN NOT NULL,
stc INT NOT NULL);

CREATE TABLE emp (
eid INT PRIMARY KEY NOT NULL UNIQUE,
user TEXT NOT NULL UNIQUE,
pass TEXT NOT NULL);


